# Generated by Django 6.0.6 on 2026-07-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], default='L', max_length=1)),
                ('birth_date', models.DateField()),
                ('admission_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('sakit', 'Sakit'), ('dikembalikan', 'Dikembalikan')], default='active', max_length=20)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
